PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Document (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Document_History (
    did TEXT NOT NULL,
    modified_at DATETIME NOT NULL,
    FOREIGN KEY (did) REFERENCES Document(id) ON DELETE CASCADE ON UPDATE CASCADE   
);

CREATE TABLE IF NOT EXISTS Category (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO Category (id, name) VALUES
('1', 'IT'),
('2', 'BA'),
('3', 'EE'),
('4', 'EN');

CREATE TABLE IF NOT EXISTS File (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    cid TEXT NOT NULL,
    author TEXT NOT NULL,
    description TEXT NOT NULL,
    did TEXT NOT NULL,
    FOREIGN KEY (did) REFERENCES Document(id) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (cid) REFERENCES Category(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS File_History (
    fid TEXT NOT NULL,
    modified_at DATETIME NOT NULL,
    FOREIGN KEY (fid) REFERENCES File(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;